//author api req
//author registration
post http://localhost:4000/author-api/author
Content-Type: application/json

{
    "userType":"author",
    "username":"vikas",
    "password":"vikas",
    "email":"vikas@gmail.com"
}

//author login
###
post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "userType":"author",
    "username":"vikas",
    "password":"vikas"
}
###

###
post http://localhost:4000/author-api/article
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzE3NTY4ODcyLCJleHAiOjE3MTc2NTUyNzJ9.vkB8vjbk0MUI2V4V0ugChpUeImW86lHJ61DB8JeoXCE
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title":"Fundamentals of Javascript part 2",
    "category":"programming",
    "content":"JavaScript, often abbreviated as JS, is a programming language and core technology of the World Wide Web, alongside HTML and CSS. 99% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries. ",
    "dateOfCreation":"{{$datetime iso8601}}",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"vikas",
    "comments":[],
    "status":true
}

//modify or update article by author
###
put http://localhost:4000/author-api/article
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzE4NjkwODIwLCJleHAiOjE3MTg3NzcyMjB9.KOi5M-MFdBiuKB-MLB993SnRSbWknEaFW2-ilby5vxU
Content-Type: application/json

{
    "articleId":"1710421020",
    "title":"Fundamentals of Javascript",
    "category":"programming",
    "content":" JS is a programming language and core technology of the World Wide Web, alongside HTML and CSS. 99% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries. ",
    "dateOfCreation":"2024-03-14T12:57:00.447Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"vikas",
    "comments":[],
    "status":true
}

//soft delete an article by article id
###
put http://localhost:4000/author-api/article/1710421020
Content-Type: application/json

{
    "articleId":"1710421020",
    "title":"Fundamentals of Javascript",
    "category":"programming",
    "content":" JS is a programming language and core technology of the World Wide Web, alongside HTML and CSS. 99% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries. ",
    "dateOfCreation":"2024-03-14T12:57:00.447Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"vikas",
    "comments":[],
    "status":true
}

//view articles
###
get http://localhost:4000/author-api/articles/vikas

